### ISSUE TITLE
在vue2.x中使用计算属性computed的问题

### ISSUE THREAD

**Issue by scriptChuang** [baukh789/GridManager-Angular-1.x#17]
请教大神，vue里面使用通栏模式，模板当中应该怎么使用计算属性呢？fullColumn.topTemplate以及columnData.template，如图，我这么写了，但是报错了，是我的写法不对吗？
![image](https://user-images.githubusercontent.com/22783440/118639137-28492c80-b80a-11eb-99e8-73d9c7c05530.png)
![image](https://user-images.githubusercontent.com/22783440/118639376-6c3c3180-b80a-11eb-80ec-c5c6873496b6.png)

**Comment by baukh789** [comment]
这个组件是原生JS组件，目前只支持Vue中常用的内置函数。
针对于你所提到的问题，可以尝试将computed的函数放至mounted或工具类中。

另外这个github的地址是angular-1.x的地址。

**Comment by scriptChuang** [comment]
谢谢你的回复，我发布之后才发现发错地方了。。
