### ISSUE TITLE
请问后续有支持IE的计划吗 ？

### ISSUE THREAD

**Issue by Lnastacies** [baukh789/GridManager-Angular-1.x#2]
以前的angular1.x项目，暂时还有部分IE用户，需要继续支持使用！
看到这个项目前端做的非常棒，只是可惜不能兼容IE。

**Comment by baukh789** [comment]
这个项目是[GridManager](https://github.com/baukh789/GridManager)的一个包装项目，不支持IE的原因是由于在设计GridManager的时候并未考虑兼容IE的问题。
已经有不少的人提到了这个问题，我也在考虑是否可以实现。

**Comment by Lnastacies** [comment]
> 这个项目是[GridManager](https://github.com/baukh789/GridManager)的一个包装项目，不支持IE的原因是由于在设计GridManager的时候并未考虑兼容IE的问题。
> 已经有不少的人提到了这个问题，我也在考虑是否可以实现。

看到项目已经支持了很多前端框架，我用ng-grid实现了大部分功能，可以兼容IE，但是没有你这个完善，膜拜
